version: "3.4"

networks:
  default:
    driver: bridge

services: 
  frontend:
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
      target: production-stage
    links: 
      - backend
    ports: 
      - "9000:80"
    environment:
      ROVANIEMI_BACKEND: backend:3000

  backend:
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile
      target: production-stage
    ports: 
      - "9001:3000"
    environment:
      ROVANIEMI_DB_HOST: db:3306
      ROVANIEMI_DB_NAME: rovaniemi
      ROVANIEMI_DB_USER: root
      ROVANIEMI_DB_PASSWORD: '2#q#eMzTXXSMZ9F5'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'rovaniemi'
      MYSQL_ROOT_PASSWORD: '2#q#eMzTXXSMZ9F5'
    ports:
      - "9002:3306"
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data: {}
