version: "3.4"

networks:
  default:
    driver: bridge

services: 
  frontend:
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile-dev
    links: 
      - backend
    ports: 
      - "9000:80"
    environment:
      ROVANIEMI_BACKEND: backend:3000

  backend:
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile-dev
    ports: 
      - "9001:3000"
    environment:
      ROVANIEMI_DB_HOST: db
      ROVANIEMI_DB_NAME: rovaniemi
      ROVANIEMI_DB_USER: root
      ROVANIEMI_DB_PASSWORD: root
      JWT_SECRET: "obsapnTVQoP29JjusZdy"
    links:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'rovaniemi'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
