version: "3.4"

networks:
  inside:
    internal: true
  outside:

services: 
  frontend:
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
      target: production-stage
    links: 
      - backend
    ports: 
      - "9000:80"
    environment:
      ROVANIEMI_BACKEND: localhost:9001
    networks:
      - outside

  backend:
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile
      target: production-stage
    ports: 
      - "9001:3000"
    environment:
      ROVANIEMI_DB_HOST: db:3306
      ROVANIEMI_DB_NAME: rovaniemi
      ROVANIEMI_DB_USER: root
      ROVANIEMI_DB_PASSWORD: root
      JWT_SECRET: "obsapnTVQoP29JjusZdy"
    links:
      - db
    networks:
      - inside
      - outside

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'rovaniemi'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - inside
